-- INSERT INTO movies (title, year, category) VALUES ('The Godfather', 1972, 'Crime');
-- INSERT INTO movies (title, year, category) VALUES ('Terminator 2: Judgment Day', 1991, 'Action/Sci-fi');
-- INSERT INTO movies (title, year, category) VALUES ('Reservoir Dogs', 1992, 'Crime');
-- INSERT INTO movies (title, year, category) VALUES ('Tombstone', 1993, 'Western/Action');
-- INSERT INTO movies (title, year, category) VALUES ('The Nightmare Before Christmas', 1993, 'Animation/Family');
-- INSERT INTO movies (title, year, category) VALUES ('Jurassic Park', 1993, 'Adventure/Sci-fi');
-- INSERT INTO movies (title, year, category) VALUES ('Léon: The Professional', 1994, 'Action/Drama');
-- INSERT INTO movies (title, year, category) VALUES ('Pulp Fiction', 1994, 'Comedy/Crime');
-- INSERT INTO movies (title, year, category) VALUES ('The Crow', 1994, 'Action/Fantasy');
-- INSERT INTO movies (title, year, category) VALUES ('Interview with the Vampire', 1994, 'Horror/Romance');
-- INSERT INTO movies (title, year, category) VALUES ('The Usual Suspects', 1995, 'Thriller/Mystery');
-- INSERT INTO movies (title, year, category) VALUES ('Heat', 1995, 'Crime');
-- INSERT INTO movies (title, year, category) VALUES ('Jumanji', 1995, 'Family/Adventure');
-- INSERT INTO movies (title, year, category) VALUES ('Desperado', 1995, 'Action/Western');
-- INSERT INTO movies (title, year, category) VALUES ('Mortal Kombat', 1995, 'Action/Adventure');
-- INSERT INTO movies (title, year, category) VALUES ('Pocahontas', 1995, 'Animation/Musical');
-- INSERT INTO movies (title, year, category) VALUES ('Mulan', 1998, 'Animation/Family');
-- INSERT INTO movies (title, year, category) VALUES ('Matilda', 1996, 'Family/Comedy');
-- INSERT INTO movies (title, year, category) VALUES ('Space Jam', 1996, 'Animation/Family');
-- INSERT INTO movies (title, year, category) VALUES ('Trainspotting', 1996, 'Crime');
-- INSERT INTO movies (title, year, category) VALUES ('Princess Mononoke', 1997, 'Animation/Fantasy');
-- INSERT INTO movies (title, year, category) VALUES ('The Fifth Element', 1997, 'Action/Sci-fi');
-- INSERT INTO movies (title, year, category) VALUES (E'The Devil\'s Advocate', 1997, 'Thriller/Horror');
-- INSERT INTO movies (title, year, category) VALUES ('The Big Lebowski', 1998, 'Action/Sci-fi');
-- INSERT INTO movies (title, year, category) VALUES ('Blade', 1998, 'Action/Horror');
-- INSERT INTO movies (title, year, category) VALUES ('Dark City', 1998, 'Sci-fi/Noir');
-- INSERT INTO movies (title, year, category) VALUES ('What Dreams May Come', 1998, 'Romance/Fantasy');
-- INSERT INTO movies (title, year, category) VALUES ('Lock, Stock and Two Smoking Barrels', 1998, 'Crime/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('The Matrix', 1999, 'Action/Sci-fi');
-- INSERT INTO movies (title, year, category) VALUES ('Fight Club', 1999, 'Drama/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('The Mummy', 1999, 'Action/Adventure');
-- INSERT INTO movies (title, year, category) VALUES ('Office Space', 1999, 'Comedy/Dark Comedy');
-- INSERT INTO movies (title, year, category) VALUES ('The Iron Giant', 1999, 'Animation/Family');
-- INSERT INTO movies (title, year, category) VALUES ('Snatch', 2000, 'Comedy/Heist');
-- INSERT INTO movies (title, year, category) VALUES ('Donnie Darko', 2001, 'Sci-fi/Fantasy');
-- INSERT INTO movies (title, year, category) VALUES ('Spirited Away', 2001, 'Animation/Fantasy');
-- INSERT INTO movies (title, year, category) VALUES ('Hero', 2002, 'Action/Drama');
-- INSERT INTO movies (title, year, category) VALUES ('The Transporter', 2002, 'Action/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('Kill Bill: Volume 1', 2003, 'Action/Martial Arts');
-- INSERT INTO movies (title, year, category) VALUES ('Underworld', 2003, 'Action/Horror');
-- INSERT INTO movies (title, year, category) VALUES ('Layer Cake', 2004, 'Crime/Drama');
-- INSERT INTO movies (title, year, category) VALUES ('Constantine', 2005, 'Horror/Fantasy');
-- INSERT INTO movies (title, year, category) VALUES ('V for Vendetta', 2005, 'Action/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('The Protector', 2005, 'Action/Martial Arts');
-- INSERT INTO movies (title, year, category) VALUES ('Fearless', 2006, 'Action/Martial Arts');
-- INSERT INTO movies (title, year, category) VALUES ('Idiocracy', 2006, ' Comedy/Sci-fi');
-- INSERT INTO movies (title, year, category) VALUES ('The Departed', 2006, 'Thriller/Crime');
-- INSERT INTO movies (title, year, category) VALUES (E'Smokin\' Aces', 2006, 'Action/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('American Gangster', 2007, 'Crime/Drama');
-- INSERT INTO movies (title, year, category) VALUES ('I Am Legend', 2007, 'Sci-fi/Horror');
-- INSERT INTO movies (title, year, category) VALUES ('The Dark Knight', 2008, 'Action/Adventure');
-- INSERT INTO movies (title, year, category) VALUES ('Ip Man', 2008, 'Action/Drama');
-- INSERT INTO movies (title, year, category) VALUES ('Watchmen', 2009, 'Action/Adventure');
-- INSERT INTO movies (title, year, category) VALUES ('Blood and Bone', 2009, 'Action/Martial Arts');
-- INSERT INTO movies (title, year, category) VALUES ('Zombieland', 2009, 'Comedy/Horror');
-- INSERT INTO movies (title, year, category) VALUES ('Inception', 2010, 'Action/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('John Wick', 2014, 'Action/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('Ex Machina', 2014, 'Sci-fi/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('Arrival', 2016, 'Sci-fi/Thriller');
-- INSERT INTO movies (title, year, category) VALUES ('Keanu', 2016, 'Comedy/Action');
-- INSERT INTO movies (title, year, category) VALUES ('Knives Out', 2019, 'Mystery/Comedy');
-- INSERT INTO movies (title, year, category) VALUES ('Parasite', 2019, 'Thriller/Comedy');

INSERT INTO categories (category) VALUES ('Action');
INSERT INTO categories (category) VALUES ('Animation');
INSERT INTO categories (category) VALUES ('Comedy');
INSERT INTO categories (category) VALUES ('Crime');
INSERT INTO categories (category) VALUES ('Drama');
INSERT INTO categories (category) VALUES ('Fantasy');
INSERT INTO categories (category) VALUES ('Horror');
INSERT INTO categories (category) VALUES ('Mystery');
INSERT INTO categories (category) VALUES ('Sci-fi');
INSERT INTO categories (category) VALUES ('Western');

INSERT INTO movies (title, year, category_id) VALUES ('Tombstone', 1993, 10);
INSERT INTO movies (title, year, category_id) VALUES ('Princess Mononoke', 1997, 2);
INSERT INTO movies (title, year, category_id) VALUES ('The Matrix', 1999, 9);
INSERT INTO movies (title, year, category_id) VALUES ('Fight Club', 1999, 5);
INSERT INTO movies (title, year, category_id) VALUES ('Donnie Darko', 2001, 9);
INSERT INTO movies (title, year, category_id) VALUES ('Layer Cake', 2004, 4);
INSERT INTO movies (title, year, category_id) VALUES ('Constantine', 2005, 6);
INSERT INTO movies (title, year, category_id) VALUES ('V for Vendetta', 2005, 1);
INSERT INTO movies (title, year, category_id) VALUES ('Keanu', 2016, 3);
INSERT INTO movies (title, year, category_id) VALUES ('The Ritual', 2017, 7);
INSERT INTO movies (title, year, category_id) VALUES ('Knives Out', 2019, 8);