package com.launchacademy.marathon.seeders;

import com.launchacademy.marathon.models.Song;
import com.launchacademy.marathon.repositories.SongRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import java.util.ArrayList;
import java.util.List;

@Component
public class SongSeeder implements CommandLineRunner {
  @Autowired private SongRepository songRepository;

  @Override
  public void run(String... args) throws Exception {
    List<Song> songs = new ArrayList<>();

    Song song = new Song();
    song.setTitle("Don Henley — American Pie");
    song.setGenre("Rock");
    song.setReleaseYear(1971);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Pixies — Where Is My Mind?");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(1988);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Daylight");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2001);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — No Regrets");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2001);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Battery");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2001);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — 9-5ers Anthem");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2001);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Zodiaccupuncture");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2005);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — None Shall Pass");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2007);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Citronella");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2007);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Coffee");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2007);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Cycles to Gehenna");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2012);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Zero Dark Thirty");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2012);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Crows 1");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2012);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Aesop Rock — Crows 2");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2012);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Atmosphere — Became");
    song.setGenre("Hip Hop");
    song.setReleaseYear(2011);
    song.setExplicitContent(true);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — Monster");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2011);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — Poison");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2012);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — Desire");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2014);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — Heart Heart Head");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2014);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — Motel");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2015);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — Sorry");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2015);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — A Bolt From the Blue");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2015);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — Numb");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2018);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Meg Myers — Jealous Sea");
    song.setGenre("Alternative Rock");
    song.setReleaseYear(2018);
    song.setExplicitContent(false);
    songs.add(song);
    song = new Song();
    song.setTitle("Gary Jules — Mad World");
    song.setGenre("Soft Rock");
    song.setReleaseYear(2001);
    song.setExplicitContent(false);
    songs.add(song);

    for(Song track : songs) { if(!songRepository.existsByTitle(track.getTitle())) { songRepository.save(track); } }
  }
}